name: monitoring_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  provider:
  # rename_app: ^1.3.2
  timeago:
  fluttertoast:
  connectivity_plus:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # flutter_launcher_icons: "^0.13.1"

  
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/logo.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   web:
#     generate: false
#     image_path: "path/to/image.png"
#     background_color: "#hexcode"
#     theme_color: "#hexcode"
#   windows:
#     generate: true
#     image_path: "path/to/image.png"
#     icon_size: 48 # min:48, max:256, default: 48
#   macos:
#     generate: false
#     image_path: "path/to/image.png"
assets:
 - assets/

flutter:
  uses-material-design: true
